//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int Orderid { get; set; }
        public string Ordername { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Img { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
